services:
  app:
    build: .
    container_name: wfh_stress_app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
      DB_NAME: "wfh_stress_db"
      MODEL_PATH: "/app/backend/tuned_model.pkl"
      SECRET_KEY: "change-this-secret"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: wfh_stress_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: